# Generated by Django 4.2.1 on 2023-09-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamequota_gamequotalineup_gamequota_lineups'),
        ('players', '0004_player_game_alter_player_team'),
        ('teams', '0004_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('memo', models.TextField(blank=True)),
                ('carry_over', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('memo', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='since',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamVoteBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tballots', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tballots', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('candidates', models.ManyToManyField(related_name='candidated_tvotes', to='players.player')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_tvotes', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvotes', to='teams.team')),
                ('winners', models.ManyToManyField(blank=True, related_name='winner_tvotes', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dateTime', models.DateTimeField()),
                ('category', models.CharField(choices=[('plan', 'Plan'), ('game', 'Game')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamNoti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dateTime', models.DateTimeField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('tom', 'Tom'), ('vote', 'Vote'), ('game', 'Game'), ('plan', 'Plan')], max_length=20)),
                ('payload', models.TextField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notis', to='games.game')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notis', to='teams.teamschedule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notis', to='teams.team')),
                ('tvote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notis', to='teams.teamvote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('payload', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuesPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.CharField(choices=[('non', 'Non'), ('paid', 'Paid'), ('non_paid', 'Non_Paid'), ('na', 'Na')], max_length=20)),
                ('dues_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_payment_items', to='teams.duespayment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_payment_items', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='duespayment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_payments', to='teams.team'),
        ),
        migrations.CreateModel(
            name='DuesOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=150)),
                ('dues_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_out_items', to='teams.duesdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuesInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=150)),
                ('dues_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_in_items', to='teams.duesdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='duesdetail',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_details', to='teams.team'),
        ),
    ]
