# Generated by Django 4.2.1 on 2023-09-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_duesdetail_duespayment_team_code_alter_team_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duespaymentitem',
            name='payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('non_paid', 'Non_Paid'), ('na', 'Na')], max_length=20),
        ),
    ]
