# Generated by Django 4.2.1 on 2023-09-21 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0006_alter_duespaymentitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='spvsr',
        ),
        migrations.AddField(
            model_name='team',
            name='founder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_founder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='spvsrs',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
