# Generated by Django 4.2.1 on 2023-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_team_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='plan',
            field=models.CharField(blank=True, default='basic', max_length=150, null=True),
        ),
    ]
