# Generated by Django 4.2.1 on 2023-09-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_team_code_alter_team_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
        migrations.RemoveField(
            model_name='team',
            name='plan',
        ),
    ]
