# Generated by Django 4.2.1 on 2023-06-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_vote_participants'),
        ('medias', '0004_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='player',
        ),
        migrations.AddField(
            model_name='photo',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='games.game'),
        ),
    ]
