# Generated by Django 4.2.1 on 2023-09-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_duesdetail_duespayment_team_code_alter_team_since_and_more'),
        ('medias', '0005_remove_photo_player_photo_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='teams.teamfeed'),
        ),
    ]
