# Generated by Django 4.2.1 on 2023-05-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='candidates',
            field=models.ManyToManyField(related_name='candidated_votes', to='players.player'),
        ),
        migrations.AddField(
            model_name='vote',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='games.game'),
        ),
        migrations.AddField(
            model_name='vote',
            name='participants',
            field=models.ManyToManyField(related_name='participated_votes', to='players.player'),
        ),
        migrations.AddField(
            model_name='goalplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='games.game'),
        ),
        migrations.AddField(
            model_name='goalplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='players.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(related_name='games', to='players.player'),
        ),
    ]
