# Generated by Django 4.2.1 on 2023-05-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='game',
            name='vsteam',
            field=models.CharField(max_length=180),
        ),
    ]
