# Generated by Django 4.2.1 on 2023-05-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_location_alter_game_vsteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='vsteam_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
