# Generated by Django 4.2.1 on 2023-05-19 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_team_score_alter_game_vsteam_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='start_time',
        ),
        migrations.AddField(
            model_name='vote',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
