# Generated by Django 4.2.1 on 2023-05-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('games', '0008_voteballot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_votes', to='players.player'),
        ),
    ]
