# Generated by Django 4.2.1 on 2023-09-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_description'),
        ('games', '0009_alter_vote_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.CharField(choices=[('4-4-2', '4-4-2'), ('4-2-3-1', '4-2-3-1'), ('3-5-2', '3-5-2')], max_length=150)),
                ('memo', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='games.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameQuotaLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('game_quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamequota')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'unique_together': {('game_quota', 'player', 'order')},
            },
        ),
        migrations.AddField(
            model_name='gamequota',
            name='lineups',
            field=models.ManyToManyField(related_name='quotas', through='games.GameQuotaLineup', to='players.player'),
        ),
    ]
